version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - govet
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - fmt.*
        - io/ioutil.Read.*
        - io.Close
        - os.Close
        - io/fs.Close
    goconst:
      min-len: 2
      min-occurrences: 2
    govet:
      enable:
        - shadow
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - mnd
        path: _test\.go
      - linters:
          - lll
        source: '//go:generate '
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/go-generalize/go-easyparser
  exclusions:
    generated: lax
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
